---
hooks:
  build:
    - source /opt/cpanel/ea-nodejs18/bin/enable_nodejs18
    - npm install --legacy-peer-deps
    - npm run build
    - export DEPLOYPATH=~/public_html
    - /bin/cp -R dist/* $DEPLOYPATH/
  start:
    - npm start
  stop:
    - echo "Stopping app..."
  restart:
    - npm restart
  post_deploy:
    - echo "Deployment complete."
