---
hooks:
  build:
    - npm install
    - npm run build
    - export DEPLOYPATH=/home/USERNAME/public_html
    - /bin/cp -R dist/* $DEPLOYPATH/
  start:
    - npm start
  stop:
    - echo "Stopping app..."
  restart:
    - npm restart
  post_deploy:
    - echo "Deployment complete."
