CREATE TABLE IF NOT EXISTS Vehicle (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  asset_code VARCHAR(64) NOT NULL UNIQUE,
  rego VARCHAR(64),
  vin VARCHAR(64),
  asset_type VARCHAR(64),
  vehicle_function_class VARCHAR(64),
  tma_variant VARCHAR(64),
  make VARCHAR(64),
  model VARCHAR(64),
  year INT,
  state VARCHAR(16),
  primary_depot VARCHAR(128),
  status VARCHAR(32),
  in_service_date DATETIME,
  out_of_service_date DATETIME,
  ownership_type VARCHAR(32),
  hire_provider_id BIGINT,
  contract_id BIGINT,
  current_odometer_km INT,
  odometer_data_confidence VARCHAR(16),
  assignar_tracked TINYINT(1),
  assignar_asset_id VARCHAR(64),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_vehicle_state (state),
  INDEX idx_vehicle_ownership (ownership_type)
);

CREATE TABLE IF NOT EXISTS MaintenanceTemplate (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128),
  vehicle_function_class VARCHAR(64),
  asset_type VARCHAR(64),
  trigger_type VARCHAR(32),
  interval_days INT,
  interval_km INT,
  interval_hours INT,
  priority VARCHAR(32),
  hvnl_relevance_flag TINYINT(1),
  task_summary TEXT,
  checklist_items JSON,
  active TINYINT(1),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MaintenancePlan (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  maintenance_template_id BIGINT,
  last_completed_date DATETIME,
  last_completed_odometer_km INT,
  next_due_date DATETIME,
  next_due_odometer_km INT,
  status VARCHAR(32),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_plan_vehicle (vehicle_id),
  INDEX idx_plan_due_date (next_due_date)
);

CREATE TABLE IF NOT EXISTS MaintenanceWorkOrder (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  maintenance_plan_id BIGINT,
  maintenance_template_id BIGINT,
  linked_prestart_defect_id BIGINT,
  linked_incident_id BIGINT,
  work_order_type VARCHAR(32),
  raised_from VARCHAR(32),
  raised_datetime DATETIME,
  due_date DATETIME,
  status VARCHAR(32),
  priority VARCHAR(32),
  linked_service_record_id BIGINT,
  assigned_to_workshop_name VARCHAR(128),
  assigned_to_hire_provider_id BIGINT,
  purchase_order_number VARCHAR(64),
  confirmed_downtime_hours INT,
  completion_confirmed_by_user_id BIGINT,
  completion_confirmed_at DATETIME,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_wo_vehicle (vehicle_id),
  INDEX idx_wo_raised (raised_datetime),
  INDEX idx_wo_status (status)
);

CREATE TABLE IF NOT EXISTS ServiceRecord (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  service_date DATETIME,
  service_type VARCHAR(32),
  workshop_name VARCHAR(128),
  hire_provider_id BIGINT,
  cost_ex_gst DECIMAL(10,2),
  labour_cost DECIMAL(10,2),
  parts_cost DECIMAL(10,2),
  cost_chargeable_to VARCHAR(32),
  cost_anomaly_flag TINYINT(1),
  cost_anomaly_reason VARCHAR(256),
  invoice_number VARCHAR(64),
  odometer_km INT,
  downtime_start DATETIME,
  downtime_end DATETIME,
  downtime_hours INT,
  downtime_chargeable_to VARCHAR(32),
  downtime_billable_flag TINYINT(1),
  source_system VARCHAR(64),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_service_vehicle (vehicle_id),
  INDEX idx_service_date (service_date)
);

CREATE TABLE IF NOT EXISTS AssetDowntimeEvent (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  hire_provider_id BIGINT,
  start_datetime DATETIME,
  end_datetime DATETIME,
  downtime_hours INT,
  reason VARCHAR(64),
  cause_category VARCHAR(64),
  caused_by VARCHAR(32),
  chargeable_to VARCHAR(32),
  stand_down_expected TINYINT(1),
  stand_down_confirmed TINYINT(1),
  linked_service_id BIGINT,
  linked_work_order_id BIGINT,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_downtime_vehicle (vehicle_id),
  INDEX idx_downtime_start (start_datetime)
);

CREATE TABLE IF NOT EXISTS UsageRecord (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  usage_date DATETIME,
  shifts_count INT,
  shift_type VARCHAR(32),
  km_travelled INT,
  jobs_count INT,
  primary_job_number VARCHAR(64),
  project_code VARCHAR(64),
  source VARCHAR(32),
  is_offline TINYINT(1),
  offline_reason VARCHAR(128),
  ownership_type_snapshot VARCHAR(32),
  hire_provider_id_snapshot BIGINT,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_usage_vehicle (vehicle_id),
  INDEX idx_usage_date (usage_date)
);

CREATE TABLE IF NOT EXISTS PrestartCheck (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  prestart_type VARCHAR(32),
  assignar_form_id VARCHAR(64),
  assignar_prestart_id VARCHAR(64),
  prestart_datetime DATETIME,
  worker_name VARCHAR(128),
  worker_external_id VARCHAR(64),
  client_name VARCHAR(128),
  project_name VARCHAR(128),
  project_code VARCHAR(64),
  odometer_km INT,
  odometer_source VARCHAR(32),
  odometer_confidence VARCHAR(16),
  overall_result VARCHAR(16),
  defect_count INT,
  shift_type VARCHAR(32),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_prestart_vehicle (vehicle_id),
  INDEX idx_prestart_datetime (prestart_datetime)
);

CREATE TABLE IF NOT EXISTS PrestartDefect (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  prestart_id BIGINT,
  vehicle_id BIGINT,
  defect_description TEXT,
  severity VARCHAR(16),
  status VARCHAR(32),
  reported_at DATETIME,
  closed_at DATETIME,
  linked_service_id BIGINT,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_defect_vehicle (vehicle_id),
  INDEX idx_defect_reported (reported_at)
);

CREATE TABLE IF NOT EXISTS IncidentRecord (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  incident_datetime DATETIME,
  vehicle_id BIGINT,
  driver_name VARCHAR(128),
  driver_external_id VARCHAR(64),
  incident_type VARCHAR(32),
  severity VARCHAR(16),
  description TEXT,
  location VARCHAR(128),
  project_code VARCHAR(64),
  client_name VARCHAR(128),
  injuries_reported TINYINT(1),
  damage_cost DECIMAL(10,2),
  hvnl_breach_type VARCHAR(64),
  investigation_status VARCHAR(32),
  status VARCHAR(32),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_incident_vehicle (vehicle_id),
  INDEX idx_incident_datetime (incident_datetime)
);

CREATE TABLE IF NOT EXISTS FuelTransaction (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id BIGINT,
  transaction_datetime DATETIME,
  litres DECIMAL(10,2),
  total_cost DECIMAL(10,2),
  unit_price DECIMAL(10,4),
  site_location VARCHAR(128),
  fuel_type VARCHAR(32),
  card_number VARCHAR(64),
  supplier_name VARCHAR(128),
  source VARCHAR(32),
  source_reference VARCHAR(64),
  ownership_type_snapshot VARCHAR(32),
  hire_provider_id_snapshot BIGINT,
  odometer_at_fill INT,
  project_code VARCHAR(64),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_fuel_vehicle (vehicle_id),
  INDEX idx_fuel_datetime (transaction_datetime)
);

CREATE TABLE IF NOT EXISTS WorkerRiskStatus (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  worker_name VARCHAR(128),
  worker_external_id VARCHAR(64),
  current_risk_level VARCHAR(16),
  previous_risk_level VARCHAR(16),
  risk_score INT,
  first_detected_datetime DATETIME,
  last_updated_datetime DATETIME,
  failed_prestarts_90d INT,
  critical_defects_90d INT,
  incidents_12m INT,
  hvnl_incidents_12m INT,
  at_fault_count INT,
  escalation_sent TINYINT(1),
  alert_sent TINYINT(1),
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_worker_risk_updated (last_updated_datetime)
);
